### ISSUE TITLE
Are declined responses being retrieved by default when querying GetClickwrapAgreements without options?

### ISSUE THREAD

**Issue by NJarZe** [docusign/docusign-click-csharp-client#8]
More of a question than an actual issue, since I could not get a clear answer from the API documentation or the SDK. 

I have a call to the GetClickwrapAgreements(accountId, clickwrapId) method for a clickwrap that is storing declined responses; however, those responses are not coming back in the GetClickwrapAgreements response.

Do I need to make two calls, one for accepted and one for declined responses, using the options object?

Thanks!

**Comment by InbarGazit** [comment]
the default status (if not provided) is set to 'accept'. So GetClickwrapAgreements will return only agreed clickwraps. If the you wish to look for declined, then the status parameter must be sent. (agreed or declined)

**Comment by NJarZe** [comment]
Indeed, I figured it out by trial and error. 
To solve this, I ended up doing two api calls, one for agreed and one for declined; I then combine the two responses elsewhere. 
Thanks for clarifying!
